name: Run Unit Tests
on:
  # only execute if python file is changed
  push:
    paths:
      - '**.py'
      - '**.ipynb'
      - '**.whl'
jobs:
  build:
    # only execute if last push not from github-actions[bot]
    if: github.actor != 'github-actions[bot]' && github.event_name == 'push' && github.event.head_commit.message != 'Update version.json with latest commit code'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Install exiftool
      run: |
        sudo apt-get update
        sudo apt-get install -y libimage-exiftool-perl
    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)" >> $GITHUB_ENV
    - name: Run tests
      # GOAL: python -m unittest discover -s . -p 'test*.py' -> Problem not fiinding setup file
      # ALSO bad with MetaDataEditor cant load Qt and exiftool: python -m unittest discover -s MetaDataEditor/unittests
      run: |
        python -m unittest discover -s file_manager/unittests