on:
  push:
    branches:
      - master
jobs:
  update-version-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Check if commit author is GitHub Actions bot
        id: check_bot
        run: echo "::set-output name=is_bot::$(if [ $(git log -1 --pretty=format:'%ae') == 'actions@github.com' ]; then echo true; else echo false; fi)"
      - name: Exit if commit is made by GitHub Actions bot
        if: steps.check_bot.outputs.is_bot == 'true'
        run: exit 0
      - name: Get commit code
        run: echo "{commit_code}={$(git rev-parse HEAD)}" >> $GITHUB_OUTPUT
        id: get_commit_code
      - name: Update version.json
        run: |
          COMMIT_HASH=$(git rev-parse --short=7 HEAD)
          sed -i "s/\"version\": \".*\"/\"version\": \"$COMMIT_HASH\"/g" version.json
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add version.json
          git commit -m "Update version.json with latest commit code"
          git push
